# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descr', models.CharField(max_length=255)),
                ('start', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('end', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
