# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_auto_20160503_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='user2event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
