# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user2event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2event',
            name='date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
